package com.eduboss.common;

public enum ReflushReportSubject {

	FINANCE_ANALYSE("FINANCE_ANALYSE", "现金流"),//现金流
    FINANCE_CONTRACT_ANALYSE("FINANCE_CONTRACT_ANALYSE", "现金流（合同）"),//现金流（合同）
	TEACHER_COURSE_CONSUME("TEACHER_COURSE_CONSUME", "老师课消"),//老师课消
    STUDENT_COURSE_CONSUME("TEACHER_COURSE_CONSUME", "老师课消（学生维度）"),//老师课消（学生维度）
	ONE_ON_ONE_COURSE_CONSUME("ONE_ON_ONE_COURSE_CONSUME", "一对一课消"),//一对一课消
	ONE_ON_ONE_STUDENT_NUMBER("ONE_ON_ONE_STUDENT_NUMBER", "一对一学生数"),//一对一学生数
	ONE_ON_ONE_REMAIN_FINANCE("ONE_ON_ONE_REMAIN_FINANCE", "一对一剩余资金"),//一对一剩余资金
	MINI_CLASS_COURSE_CONSUME("MINI_CLASS_COURSE_CONSUME", "小班课消"),//小班课消
	MINI_CLASS_STUDENT_NUMBER("MINI_CLASS_STUDENT_NUMBER", "小班学生数"),//小班学生数
	MINI_CLASS_REMAIN_FINANCE("MINI_CLASS_REMAIN_FINANCE", "小班剩余资金"),//小班剩余资金
    REFUND_ANALYZE("REFUND_ANALYZE", "退费统计"),//退费统计
    MINI_CLASS_ATTENDS_ANALYZE("MINI_CLASS_ATTENDS_ANALYZE", "小班考勤统计"),//小班考勤统计
    INCOMING_ANALYZE("INCOMING_ANALYZE", "收入统计"),//收入统计
    STUDENT_PENDING_MONEY("STUDENT_PENDING_MONEY","待收款统计"),
    MINI_CLASS_PEOPLE_ANALYZE("MINI_CLASS_PEOPLE_ANALYZE","小班产品人数统计"),
    CONTRACT_BONUS_ORGANIZATION("CONTRACT_BONUS_ORGANIZATION","业绩（校区）"),
    CONTRACT_BONUS_STAFF("CONTRACT_BONUS_STAFF","业绩（签单人）"),
    STUDENT_PAY_CLASS_HOUR("STUDENT_PAY_CLASS_HOUR","购买课时统计"),
    STUDENT_PAY_CLASS_HOUR_CAMPUS("STUDENT_PAY_CLASS_HOUR_CAMPUS","购买课时统计(校区维度)"),
	STUDENT_SURPLUS_FUNDING("STUDENT_SURPLUS_FUNDING","学生剩余资金统计（每天）"),
    STUDENT_PAY_CLASS_HOUR_EVERY_DAY("STUDENT_PAY_CLASS_HOUR_EVERY_DAY","购买课时统计(每天)"),
	MINI_CLASS_STUDENT_REAL_NUMBER("MINI_CLASS_STUDENT_REAL_NUMBER", "小班报读学生数"),//小班学生数;
	PRODUCT_MARKET_ANALYZE("PRODUCT_MARKET_ANALYZE", "产品销售统计"),//产品销售统计
	PRODUCT_CONSUME_ANALYZE("PRODUCT_CONSUME_ANALYZE", "产品消耗统计"),//产品消耗统计
	ONE_ON_ONE_STUDENT_OOO_NUMBER("ONE_ON_ONE_STUDENT_OOO_NUMBER","学生一对一状态统计"),
	ONE_TO_MANY_REMAIN_FINANCE("ONE_TO_MANY_REMAIN_FINANCE", "一对多剩余资金"),
	STUDENT_OTM_NUMBER("STUDENT_OTM_NUMBER","学生一对多状态统计"),
	MONTHLY_BALANCE("MONTHLY_BALANCE", "一对一月结"),
	FINANCE_MONTHLY_EVIDENCE("FINANCE_MONTHLY_EVIDENCE", "财务现金流凭证"),
	INCOME_MONTHLY_EVIDENCE("INCOME_MONTHLY_EVIDENCE", "财务扣费凭证"),
	INCOME_MONTHLY_CAMPUS("INCOME_MONTHLY_CAMPUS", "营收凭证"),
	REMAIN_MONTHLY_CAMPUS("REMAIN_MONTHLY_CAMPUS", "资金剩余凭证");
	
	private String value;
	private String name;
	
	private ReflushReportSubject(String value, String name) {
		this.value = value;
		this.name = name;
	}
	
	@Override
	public String toString() {
		return value;
	}


	public String getName() {
		return name;
	}

	public String getValue() {
		return value;
	}

}
